### ISSUE TITLE
website_less breaks website layout

### ISSUE THREAD

**Issue by treviser** [lukebranch/odoo-install-scripts#3]
Hi Luke
I have installed odoo using your install script on a EC2 instance with ubuntu 14.04 LTS Canonical installed. The installation seemed to be ok (ghostscript and wkhtmltopdf seemed not to install) and odoo works fine, until I install the module website_less. After that the website layout is completely broken, similar to https://www.odoo.com/forum/help-1/question/theme-clean-work-only-with-certain-user-rights-bin-bash-access-72777 (see 
![screenshot](https://cloud.githubusercontent.com/assets/1814941/5920856/ff14dd7e-a63f-11e4-86bc-1b45ca1299ec.jpg)

I assume that your install script does reflect the issues of https://github.com/odoo/odoo/issues/4604 ?
Before installing the themes I updated all modules according your advise here: https://www.odoo.com/forum/help-1/question/8-0-severe-issue-constraint-error-when-creating-chart-of-accounts-from-self-defined-account-templates-69497 and installed website_less.

**Comment by treviser** [comment]
I found the solution. After all, I have just executed the following commands as root again after the installation with Luke's script:
ln /usr/bin/nodejs /usr/bin/node
curl -L https://npmjs.org/install.sh | sh
npm install -g less less-plugin-clean-css

I took this from vilder in this issue: https://github.com/odoo/odoo/issues/4604

**Comment by lukebranch** [comment]
@treviser ,

Thanks. I'll close this for now, feel free to comment back if you feel it needs to be re-opened.

I will be adding these steps to the install script when I can find time so that this just works out of the box for new installs.
